name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git checkout -b gh-pages
          git rm -rf --cached *
          git checkout main -- build
          cp -r build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
